# Generated by Django 2.1.15 on 2021-04-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='username',
            new_name='user',
        ),
    ]
